Update Building and Using An MLOPs Stack With ZenML.ipynb
zenml-io/nba-ml-pipeline pull request #1
Opened 2022-01-26 18:10 UTC by Ben-Epstein

2022-01-27 08:28 UTC, htahir1 requested changes
Thanks for the awesome session and PR!

2022-01-27 08:28 UTC, htahir1 commented on README.md
> +pip install -r requirements_kubeflow.txt
We dont need to install these :), we do them via `zenml integration install`

2022-01-27 08:28 UTC, htahir1 commented on requirements.txt
> +sklearn
We do this via `zenml integration install`. Lets take this out and we'll create a README update for it

2022-02-01 09:22 UTC, htahir1 commented
@AlexejPenner Let's try and incoorporate @Ben-Epstein 's PR too in your PR? Ben, we're doing a big overhaul of the repo to make it more usable so these would be included

2022-02-01 09:30 UTC, AlexejPenner commented
@Ben-Epstein thanks, i'll merge this and incorporate it into the repo overhaul

2022-02-01 09:31 UTC, merged